export const skills = [
  {
    title: 'Programming Languages',
    items: [
      'Advanced: Typescript, Javascript',
      'Intermediate: Python, Java, C#',
      'Basic: Dart, Rust, Kotlin, Swift',
    ],
  },
  {
    title: 'Frontend Development',
    items: [
      'React',
      'Next.js',
      'Remix',
      'Gatsby',
      'Vue.js',
      'Webpack',
      'Vite.js',
      'Redux',
      'Mobile webview integration',
      'Micro-frontend',
      'iframe',
      'LINE LIFF applications',
    ],
  },
  {
    title: 'Backend Development',
    items: [
      'Node.js',
      'Express',
      'REST API',
      'GraphQL',
      'PostgreSQL',
      'MongoDB',
      'MySQL',
      'SQLite',
      'Keycloak',
      'State machine (xState)',
      'Headless CMS (Directus, Strapi)',
      'Low Code Platforms (Elsa, Make)',
      'Microservices',
      'Event-driven Architecture',
      'Websocket',
      'RabbitMQ',
      'Redis',
      'Smart Contracts',
      'Payment gateway integration',
      'LINE, Facebook, Discord, ChatGPT integration',
    ],
  },
  {
    title: 'Cross platform',
    items: ['React Native', 'Flutter', 'Ionic', 'Electron'],
  },
  {
    title: 'DevOps & Cloud Platforms',
    items: [
      'Docker',
      'GitHub Actions',
      'CircleCI',
      'ArgoCD',
      'AWS (S3, DynamoDB, RDS, AppSync, ECR, Athena, etc.)',
      'Firebase',
      'Heroku',
      'Vercel',
    ],
  },
  {
    title: 'Optimisation & Testing & Quality Assurance',
    items: [
      'Unit Testing',
      'E2E Testing',
      'Load Testing',
      'Benchmarking',
      'Performance Tuning',
      'Caching Strategies',
    ],
  },
  {
    title: 'Data & Analytics',
    items: ['Google Analytics', 'Time-Series Data Query', 'Fluentd'],
  },
  {
    title: 'Development Practices & Tools',
    items: ['Git', 'Jira', 'Agile Methodology', 'Code Review'],
  },
]
